version : '3'
 
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    hostname : 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - lockmanager
    
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "yourStrong(!)Password"
        ACCEPT_EULA: "Y"
    networks:
      - lockmanager
    ports:
      - 1433:1433

networks:
  lockmanager:
    driver: bridge
